### ISSUE TITLE
[Bug]: POSTGRES ERROR 53100 (disk_full)

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/devtool#197]
### What happened?

When starting the devtool (mac M1, maybe not specific to this OS), the postgres connexion crash.

### Version

devtool:alpha (mac m1)

### Relevant log output

```Shell
10:18:18.675 [notice] Application dev_tools exited: exited in: DevTool.Application.start(:normal, [])
lenra-devtool-1  |     ** (EXIT) an exception was raised:
lenra-devtool-1  |         ** (Postgrex.Error) ERROR 53100 (disk_full) could not extend file "base/16384/16392": No space left on device
lenra-devtool-1  | 
lenra-devtool-1  |     hint: Check free disk space.
lenra-devtool-1  |             (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
lenra-devtool-1  |             (ecto 3.9.4) lib/ecto/repo/schema.ex:756: Ecto.Repo.Schema.apply/4
lenra-devtool-1  |             (ecto 3.9.4) lib/ecto/repo/schema.ex:369: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
lenra-devtool-1  |             (ecto 3.9.4) lib/ecto/multi.ex:832: Ecto.Multi.apply_operation/5
lenra-devtool-1  |             (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
lenra-devtool-1  |             (ecto 3.9.4) lib/ecto/multi.ex:806: anonymous fn/5 in Ecto.Multi.apply_operations/5
lenra-devtool-1  |             (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
lenra-devtool-1  |             (db_connection 2.4.3) lib/db_connection.ex:1611: DBConnection.run_transaction/4
lenra-devtool-1  | {"Kernel pid terminated",application_controller,"{application_start_failure,dev_tools,{bad_return,{{'Elixir.DevTool.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 123,message => nil,postgres => #{code => disk_full,file => <<\"md.c\">>,hint => <<\"Check free disk space.\">>,line => <<\"462\">>,message => <<\"could not extend file \\"base/16384/16392\\": No space left on device\">>,pg_code => <<\"53100\">>,routine => <<\"mdextend\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => nil},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,913},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Repo.Schema',apply,4,[{file,\"lib/ecto/repo/schema.ex\"},{line,756}]},{'Elixir.Ecto.Repo.Schema','-do_insert/4-fun-3-',15,[{file,\"lib/ecto/repo/schema.ex\"},{line,369}]},{'Elixir.Ecto.Multi',apply_operation,5,[{file,\"lib/ecto/multi.ex\"},{line,832}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,\"lib/enum.ex\"},{line,2396}]},{'Elixir.Ecto.Multi','-apply_operations/5-fun-1-',5,[{file,\"lib/ecto/multi.ex\"},{line,806}]},{'Elixir.Ecto.Adapters.SQL','-checkout_or_transaction/4-fun-0-',3,[{file,\"lib/ecto/adapters/sql.ex\"},{line,1203}]},{'Elixir.DBConnection',run_transaction,4,[{file,\"lib/db_connection.ex\"},{line,1611}]}]}}}}}"}
lenra-devtool-1  | Kernel pid terminated (application_controller) ({application_start_failure,dev_tools,{bad_return,{{'Elixir.DevTool.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 123,message => nil,postgres => #{code => disk_full,file => <<"md.c">>,hint => <<"Check free disk space.">>,line => <<"462">>,message => <<"could not extend file \"base/16384/16392\": No space left on device">>,pg_code => <<"53100">>,routine => <<"mdextend">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => nil},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,913},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Repo.Schema',apply,4,[{file,"lib/ecto/repo/schema.ex"},{line,756}]},{'Elixir.Ecto.Repo.Schema','-do_insert/4-fun-3-',15,[{file,"lib/ecto/repo/schema.ex"},{line,369}]},{'Elixir.Ecto.Multi',apply_operation,5,[{file,"lib/ecto/multi.ex"},{line,832}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib
lenra-devtool-1  | 
lenra-devtool-1  | Crash dump is being written to: erl_crash.dump...done
```

**Comment by taorepoara** [comment]
Do you some remaining spaces ?

Try to run a 'docker-compose down --volumes' or run the magic command: 'docker system prune -a' (be careful, this last one remove many docker cache)

**Comment by Nesqwik** [comment]
Yes i do have remaining space :/ 
It seems that I don't have this issue when i start everything manually.

**Comment by taorepoara** [comment]
@shiipou Do you have any idea ?

**Comment by shiipou** [comment]
> Yes i do have remaining space :/

You can change the total space docker can access on your storage. Look at the last slider on this image :
https://i.stack.imgur.com/FKvaz.png

You can also run the command `docker system prune -a` to reclaim a lot of space if you didn't have unbound docker volumes you need to keep the data (because they will be deleted).

**Comment by shiipou** [comment]
@Nesqwik Is this issue resolved ?
